# Generated by Django 4.1.3 on 2022-12-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
